server:
  port: 8020
spring:
  application:
    name: meduo-config
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        serviceName: ${spring.application.name}	# 注册到consul的服务名称
    config:
      enabled: true
      label: master  # git仓库分支
      server:
        git:
          uri: https://github.com/gaobrian/config-repo.git  # 配置git仓库的地址
          search-paths: src/config-repo  # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: gao.brian@gmail.com  # git仓库的账号
          password: 1@#$%qWERT  # git仓库的密码
    stream:
      nats:
        server: nats://localhost:4222
        utf8-support: true
      default-binder: nats
      bindings:
        input:
          destination: dataIn
          binder: nats
        output:
          destination: dataOut
          binder: nats
management:
  endpoints:
    web:
      exposure:
        include: "*"